### ISSUE TITLE
Share refactoring

### ISSUE THREAD

**Issue by watason** [acompany-develop/QuickMPC#159]
## TODO
- [x] remove div
- [ ] remove boost operator
- [ ] create Share Base interface
  - [ ] create ShareINT ,ShareFloat ,ShareFixedPoint,ShareMod 
- [ ] create SV Base interface
   - [ ] create SV INT,Float,String?,uint8,modint
